version: '2'
services:
    jhipstersampleapplicationtest-app:
        image: jhipstersampleapplicationtest
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
